# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Schneems - Programming Practices, Performance, and Pedantry
description:      > #
  Hi, I'm Richard Schneeman. I write about Programming and Open Source.
  I run CodeTriage, the best way to get involved with OSS.
  I'm @schneems everywhere online.

# cannot have tags inside of description
rss_description:  >
  Ruby Hero.
  Runs CodeTriage.com.
  Works for Heroku.
  Posts on programming and open source."

url:              https://www.schneems.com
baseurl:          /
rss_path:         feed.xml

author:
  name:           'Richard Schneeman'
  url:            https://twitter.com/schneems

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

BASE_PATH_FOR_RSS: https://www.schneems.com

plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-redirect-from

# Assets
assets:
  css_compressor: sass
  compress:
    css: true
    js: true
  autowrite: true
  # cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"

  assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"
    - "*.webm"
    - "*.mp4"
    - "posts.css"
    - "home.css"
    - "*.js"
  digest: true
  sources:
    - "assets"
    - "assets/stylesheets"
    - "assets/images"
    - "assets/javascripts"
    - "assets/posts/img"
    - "_sass"

  features:
    liquid: true

# Random shit from the internet
include: ['dist/.well-known/', '.well-known']
exclude: ['vendor', 'bin']
